### ISSUE TITLE
Complete MVP

### ISSUE THREAD

**Issue by rcmaples** [rcmaples/trellish#7]
Need UI Styles and Mark up for:
- [x] Welcome screen
- [x] sign up form
- [x] login form 
- [x] board template
- [x] card template
- [x] sign out button
- [x] add board form

After markup, will need jquery handlers for: 
- [x] sign up
- [x] sign in
- [x] sign out
- [x] add board
- [x] add card
- [x] card modify menu
- [x] edit card
- [x] mark card as complete
- [x] mark card as favorite
- [x] mark card as priority
- [x] mark card as trash
- [x] moving card from one board to another
